version: "3"
services:
  mitt-helsingborg-io:
    build: ./repositories/mitt-helsingborg-io
    volumes:
      - "./repositories/mitt-helsingborg-io:/usr/src/app"
    ports:
      - "3030:3030"
    command: npm run dev
    environment:
      - NODE_ENV=development
      - PORT=3030
  authentication-helsingborg-io:
    build: ./repositories/authentication-helsingborg-io
    volumes:
      - "./repositories/authentication-helsingborg-io:/usr/src/app"
    ports:
      - "3031:3031"
    command: npm run dev
    environment:
      - NODE_ENV=development
      - PORT=3031
  userdata-helsingborg-io:
    build: ./repositories/userdata-helsingborg-io
    volumes:
      - "./repositories/userdata-helsingborg-io:/usr/src/app"
    ports:
      - "3032:3032"
    command: npm run dev
    environment:
      - NODE_ENV=development
      - PORT=3032
  payment-helsingborg-io:
    build: ./repositories/userdata-helsingborg-io
    volumes:
      - "./repositories/userdata-helsingborg-io:/usr/src/app"
    ports:
      - "3033:3033"
    command: npm run dev
    environment:
      - NODE_ENV=development
      - PORT=3033
  service-helsingborg-io:
    build: ./repositories/service-helsingborg-io
    volumes:
      - "./repositories/service-helsingborg-io:/usr/src/app"
    ports:
      - "3034:3034"
    command: npm run dev
    environment:
      - NODE_ENV=development
      - PORT=3034
  notification-helsingborg-io:
    build: ./repositories/notification-helsingborg-io
    volumes:
      - "./repositories/notification-helsingborg-io:/usr/src/app"
    ports:
      - "3035:3035"
    command: npm run dev
    environment:
      - NODE_ENV=development
      - PORT=3035
  chat-helsingborg-io:
    build: ./repositories/chat-helsingborg-io
    volumes:
      - "./repositories/chat-helsingborg-io:/usr/src/app"
    ports:
      - "3036:3036"
    command: npm run dev
    environment:
      - NODE_ENV=development
      - PORT=3036
  watson-helsingborg-io:
    build: ./repositories/watson-helsingborg-io
    volumes:
      - "./repositories/watson-helsingborg-io:/usr/src/app"
    ports:
      - "3037:3037"
    command: npm run dev
    environment:
      - NODE_ENV=development
      - PORT=3037
