version: "3"
services:
  mitt-helsingborg-io:
    image: mitt-helsingborg-io
    build: "https://github.com/helsingborg-stad/mitt-helsingborg-io.git"
    networks:
      - backend
  authentication-helsingborg-io:
    image: authentication-helsingborg-io
    build: "https://github.com/helsingborg-stad/authentication-helsingborg-io.git"
    networks:
      - backend
  userdata-helsingborg-io:
    image: userdata-helsingborg-io
    build: "https://github.com/helsingborg-stad/userdata-helsingborg-io.git"
    networks:
      - backend
  payment-helsingborg-io:
    image: payment-helsingborg-io
    build: "https://github.com/helsingborg-stad/payment-helsingborg-io.git"
    networks:
      - backend
  service-helsingborg-io:
    image: service-helsingborg-io
    build: "https://github.com/helsingborg-stad/service-helsingborg-io.git"
    networks:
      - backend
  notification-helsingborg-io:
    image: notification-helsingborg-io
    build: "https://github.com/helsingborg-stad/notification-helsingborg-io.git"
    networks:
      - backend
  chat-helsingborg-io:
    image: chat-helsingborg-io
    build: "https://github.com/helsingborg-stad/chat-helsingborg-io.git"
    networks:
      - backend
  watson-helsingborg-io:
    image: watson-helsingborg-io
    build: "https://github.com/helsingborg-stad/watson-helsingborg-io.git"
    networks:
      - backend
networks:
  backend:
    driver: bridge
